[project]
name = "computer-vision-group-2"
version = "0.1.0"
description = "Computer Vision Labs"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0.0",
    "pillow>=10.0.0",
    "opencv-python>=4.8.0",
    "matplotlib>=3.8.0",
]

[tool.pyrefly]
python-interpreter-path = "../.venv/Scripts/python.exe"
search-path = [
    "lab_1/src",
    ".",
]
